---
# This play runs on the remote host to build the virtual machine
# using virt-* commands
- name: Starting playbook to deploy a Centos Stream 10  virtual machine
  hosts: kvm-util.acanorex.io
  roles:
    - kvm-vm-provisioning
  vars_files:
    - vars/libvirt-centos-10-vm.yml
    - vars/vaulted/libvirt-centos-10-vm.yml
  tags:
    - create_vm
    - delete_vm
    - start_vm

