---
- name: 'Initiate base configuration of a Debian systems'
  hosts: debian_hosts
  tasks:
    - name: 'Importing the roles needed for this play...'
      ansible.builtin.import_role:
        name: debian-host-config
  vars_files:
    - vars/vaulted/vaulted-vars.yml
  tags:
    - debian_host_config 

- name: 'Configuring the dns infra services on host'
  hosts: dns_infra_hosts
  tasks:
    - name: 'Importing the roles needed for this play...'
      ansible.builtin.import_role:
        name: lab-dns-infra
  vars_files:
    - vars/vaulted/vaulted-vars.yml
  tags:
    - setup_unbound
    - debian_host_config
