---
- name: Update apt cache on Debian based hosts
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
  tags:
    - rpi_host_config
    - update_apt_cache

- name: Install packages to support Unbound dns resolver
  apt:
    name: '{{ debian_pkgs_to_install }}'
    state: latest
  when: ansible_os_family == 'Debian'
  tags:
    - rpi_host_config
    - install_pkgs
